language: c

compiler:
  - gcc
  - clang

before_install:
  - "sudo apt-get install php-dev"
  - "sudo apt-get install libextractor-dev"

before_script: 
  - "phpize"
  - "./configure"
  - "make"

script: "make test" 
