language: c

compiler: gcc

before_install:
  - "sudo apt-get install -qq php5-dev"
  - "sudo apt-get install -qq extract"
  - "sudo apt-get install -qq libextractor-dev"

before_script: 
  - "phpize"
  - "./configure"
  - "make"

script: "make test"
